#!/usr/bin/env bash
#
# .direnvrc
#
# These functions have been commented out because I am using asdf and asdf-direnv to manage tool
# versions. They were originally written for interaction with chruby. asdf-direnv uses different
# tools and these will probably be deleted in the future.

# use_ruby() {
#   local ruby_dir=$HOME/.rubies/$1
#   load_prefix "$ruby_dir"
#   layout ruby
# }

# use_python() {
#   local python_root=$PYENV_ROOT/versions/$1
#   load_prefix "$python_root"
#   if [[ -x "$python_root/bin/python" ]]; then
#     layout python "$python_root/bin/python"
#   else
#     echo "Error: $python_root/bin/python can't be executed."
#     exit
#   fi
# }

# # expected configuration for ruby projects
# if [[ -f "./.ruby-version" ]]; then
#   use_ruby "$(cat .ruby-version)"
#   PATH_add "bin"
# fi
