# mise.toml

# Don't use this, just put it in .zshrc.local
[env]

[tools]

ag = 'latest'
awscli = 'latest'
difftastic = 'latest'
direnv = 'latest'
elixir = 'latest'
erlang = 'latest'
eza = 'latest'
hugo = 'latest'
jq = 'latest'
nodejs = 'latest'
perl = 'latest'
ripgrep = 'latest'
ruby = 'latest'
shellcheck = 'latest'
sqlite = 'latest'
starship = 'latest'
yq = 'latest'

[plugins]
