# ~/.config/mise/config.toml

# Don't use this, just put it in .zshrc.local
[env]

[tools]

# programming languages
elixir = "latest"
erlang = "latest"
nodejs = "latest"
perl = "latest"
ruby = "latest"
rust = "latest"

# tools
"cargo:eza" = "latest"
"npm:prettier" = "latest"
"ubi:ajeetdsouza/zoxide" = "latest"
"ubi:cantino/mcfly" = "latest"
"ubi:casey/just" = "latest"
"ubi:dandavison/delta" = "latest"
"ubi:zellij-org/zellij" = "latest"
ag = "latest"
bitwarden = "latest"
chezmoi = "latest"
duckdb = "latest"
jq = "latest"
ripgrep = "latest"
shellcheck = 'latest'
sqlite = "latest"
starship = "latest"
yq = "latest"

[plugins]

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]
