# ~/.config/mise/config.toml

# Don't use this, just put it in .zshrc.local
[env]

[tools]

# programming languages
deno = "latest"
elixir = "latest"
erlang = "latest"
nodejs = "latest"
perl = "latest"
ruby = "latest"
rust = "latest"

# tools
bitwarden = "latest"
bitwarden-secrets-manager = "latest"
duckdb = "latest"
shellcheck = "latest"
sqlite = "latest"
taplo = "latest"
usage = "latest"
pre-commit = "latest"

[plugins]

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]
