# .jjconfig.toml

[user]
name = "Paul C. Mantz"
email = "pcmantz@mcpantz.org"

[ui]
default-command = "status"

diff.tool = "delta"
editor = "zile"
paginate = "auto"
pager = "bat -p"

diff-formatter = ":git"
conflict-marker-style = "git"

[git]
push-bookmark-prefix = "pcmantz/feature/"

[aliases]

cat = ["file", "show"]
ci = "commit"
credit = ["file", "annotate"]
d = "diff"
nt = ["new", "trunk()"]
rmt = ["git", "remote"]
l = ["log"]
